<?php require 'templates/layout/header.phtml' ?>
<section class="container justify-content-center" style="width: 20rem;">
    <form action="registeruser" method="POST">
        <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" name="name">
        </div>
        <div class="form-group">
            <label>Lastname</label>
            <input type="text" class="form-control" name="lastname">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="text" class="form-control" name="email">
        </div>
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" name="username">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="text" class="form-control" name="password">
        </div>
        <button type="submit" name="submit" value="registeruser" class="btn btn-primary">Submit</button>
    </form>
    <div class="d-flex flex-column align-items-center">
        <p>Do you already have an account?</p>
        <a href="loginform" class="btn-primary">Log in</a>
    </div>
</section>