<?php require 'templates/layout/header.phtml'; ?>
    <div class="container justify-content-center" style="width: 40%;">
        <form
        action="<?php echo BASE_URL; ?>saveauthor/<?php echo $author->author_id; ?>"
        method="POST"
        enctype="multipart/form-data">

            <div class="form-group">
                <label style="font-weight: bold;">Author's name</label>
                <input
                type="text"
                class="form-control"
                name="authorname"
                value="<?php echo $author->author_name; ?>">
            </div>
            <br>
            <div class="form-group">
                <label style="font-weight: bold;">Author's photo</label>
                <input
                type="file"
                name="authorimg"
                id="">
            </div>
            <br>
            <div class="form-group">
                <label style="font-weight: bold;">Author's age</label>
                <input
                type="number"
                class="form-control"
                name="authorage"
                value="<?php echo $author->author_age; ?>">
            </div>
            <br>
            <div class="form-group">
                <label style="font-weight: bold;">Author's activity</label>
                <input
                type="text"
                class="form-control"
                name="authoractivity"
                value="<?php echo $author->author_activity; ?>">
            </div>
            
            <div class="d-flex justify-content-center" style="margin-top: 5rem;">
                <button
                type="submit"
                name="submit"
                value="<?php echo BASE_URL; ?>saveauthor/<?php echo $author->author_id; ?>"
                style="
                background-color: rgb(165, 56, 107);
                margin-right: 2rem;
                margin-bottom: 4rem;
                padding: 0.3rem;
                padding-left: 0.5rem;
                padding-right: 0.5rem;
                border: 0px;
                border-radius: 0.4rem;
                color: white;
                ">
                    Submit
                </button>
                <a
                href="<?php echo BASE_URL; ?>authors">
                    Go back
                </a>
            </div>
        </form>
    </div>
<?php require './templates/layout/footer.phtml'; ?>