<div class="container">
    <div class="row justify-content-center">
        <?php foreach($authors as $author): ?>
            <div class="card col-4" style="width: 18rem;">
                <!-- <img class="card-img bookimg" src="public/statics/images/books/<?php echo $book->book_img; ?>" alt="Card image"> -->
                <div class="card-body">
                    <h5 class="card-title"><?=$author->author_name?></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><?=$author->author_age?> years old</h6>
                    <p class="card-text">Active since <?=$author->author_activity?></p>
                    <a href="book/<?=$author->author_name?>" class="card-link">Read more</a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>