<?php require './templates/layout/header.phtml'; ?>
<section class="justify-content-center align-content-center light-section">
    <div class="justify-content-center align-content-center">
        <h1 style="text-align: center;">
            Welcome to
        </h1>
        <div class="d-flex justify-content-center">
            <img
            style="margin: 3rem; height: 15rem;"
            src="public/statics/images/web-design/title.png"
            alt="Lolinwonderland title">
        </div>
        
        <h3 style="text-align: center; margin-bottom: 8rem;">
            A site made by people who love <span>books</span> to help others to find their next <span>adventure</span>.<br>
            Come and join us!
        </h3>
    </div>
    <div
    class="row justify-content-center"
    style="marig-top: 2rem;">
        <div class="col-4 sectiontitles">
            <a href="library">
                <img
                src="public/statics/images/web-design/books.png"
                alt="books icon">
            </a>
            <a href="library">
                <h2>
                    <span>Books</span>
                </h2>
            </a>
        </div>
        <div class="col-4 sectiontitles">
            <a href="authors">
                <img src="public/statics/images/web-design/authors.png" alt="authors icon">
            </a>
            <a href="authors">
                <h2>
                    <span>Authors</span>
                </h2>
            </a>
        </div>
    </div>
    <div
    class="align-items-center justify-content-center"
    style="margin-top: 8rem;">
        <img
        src="public\statics\images\web-design\background.jpg"
        alt=""
        style="width: 100%; height: 30rem;">
    </div>
</section>

<section class="d-flex justify-content-center dark-section" style="padding-top: 8rem; padding-bottom: 8rem;">
    <div class="container">
        <h2>Do you want to see a bit more of us?</h2>
        <p>
            If you want to see a little more about <span>our reviews</span> or maybe you need <span>help</span> to find a certain story, visit our YouTube Channel to see the videos we share.
            <br>
            <br>
            Not only will you find way more extensive and more detailed reviews, but also you will be able to see unboxings of special editions, interviews to our favorite authors and <span>have a lot of fun with us</span>!
            <br>
            And if you have any questions, you can <span>contact us</span> and together, we will make your new adventure real!
        </p>
    </div>
</section>
<?php require './templates/layout/footer.phtml'; ?>