<?php require 'templates/layout/header.phtml'; ?>
<div class="container">
    <div class="row justify-content-center">
        <?php foreach($library as $book): ?>
            <div class="card col-4" style="width: 18rem;">
                <img
                class="card-img"
                style="height: 12rem;"
                src="<?php echo BASE_URL; ?>public/statics/images/books/<?php echo $book->book_img; ?>"
                alt="Card image">
                <div class="card-body">
                    <h5 class="card-title">
                        <?=$book->book_name?>
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">
                        <?php foreach($authors as $author): ?>
                            <?php if($author->author_id === $book->book_authorid): ?>
                                <?= $author->author_name; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                         - Series: <?=$book->book_series?>
                    </h6>
                    <p class="card-text">
                        <?=$book->book_summary?>
                    </p>
                    <div class="d-flex justify-content-between">
                        <a
                        href="book/<?php echo $book->book_id ?>"
                        style="
                        background-color: rgb(165, 56, 107);
                        padding: 0.3rem;
                        padding-left: 0.5rem;
                        padding-right: 0.5rem;
                        border-radius: 0.4rem;
                        color: white;
                        ">
                            Read more
                        </a>
                        <?php if(isset($_SESSION['username'])): ?>
                            <div>
                                <a href="modifyForm/<?php echo $book->book_id ?>" class="card-link">
                                    Editar
                                </a>
                                <a href="erase/<?php echo $book->book_id ?>" class="card-link">
                                    Borrar
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php if(isset($_SESSION['username']) && $_SESSION['username'] == "ladypanther"): ?>
    <div
    class="container d-flex justify-content-center"
    style="padding-top: 3rem; padding-bottom: 3rem;">
        <a href="addBookForm"
        style="
        background-color: rgb(165, 56, 107);
        padding: 0.3rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        border-radius: 0.4rem;
        color: white;
        ">
            Add new book
        </a>
    </div>
<?php endif; ?>
<?php require './templates/layout/footer.php'; ?>