<nav class="mynav navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
  <a class="navbar-brand" href="<?php echo BASE_URL; ?>home"><img src="public/statics/images/web-design/logo.png" style="height: 3rem; margin-right: 1rem;" alt="">Lolinwonderland</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<?php echo BASE_URL; ?>home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo BASE_URL; ?>library">Library</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo BASE_URL; ?>authors">Authors</a>
        </li>
        <span style="display: none;"><?php session_start(); ?></span>
        <?php if(!$_SESSION): ?>
          <li class="nav-item">
            <a class="nav-link" href="loginform">Login</a>
          </li>
        <?php endif; ?>
        <?php if($_SESSION): ?>
          <li class="nav-item">
            <a class="nav-link" href="logoutuser">Logout</a>
          </li>
        <?php endif; ?>
      </ul>
    </div>
  </div>
</nav>